### ISSUE TITLE
duplicate value for resource 'attr/font' past 

### ISSUE THREAD

**Issue by amiyo-biswas** [intuit/sdp#47]
Getting duplicate value for resource **'attr/font'** past couple of hours. Need your help.

````error: duplicate value for resource 'attr/font' with config ''.
Message{kind=ERROR, text=error: duplicate value for resource 'attr/font' with config ''., sources=[C:\Users\###\.gradle\caches\transforms-1\files-1.1\sdp-android-1.0.5.aar\d513ef727a30bd4a753b67a99c92758b\res\values\values.xml:3:5-43], original message=, tool name=Optional.of(AAPT)}
````

Problem coming when I add **facebook-android-sdk**.

build.gradle

 ````
implementation 'com.intuit.sdp:sdp-android:1.0.5' 
implementation 'com.facebook.android:facebook-android-sdk:4.33.0'
````
I already tried with your old versions. Same issue. Any help would be greatly appreciated.

**Comment by amiyo-biswas** [comment]
Solved!

I just rename **attr name** from **attrs.xml** . 

````
<declare-styleable name="custom_font">
        <attr name="app_font" format="string" />
    </declare-styleable>
````

**Comment by CCorrado** [comment]
This. This saved me hours. Thanks man!

For reference my problem existed with a custom layout I built on top of Constraint Layout. Turns out in 2.0.0 (in alpha2 right now) "textColor" is now a defined stylable in the widget. So creating attrs.xml with a textColor created a duplicate resource when merging the values and hence it failed to compile. BRILLIANT!
